<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\ResourceCollection;

class UsersCollection extends ResourceCollection
{
    public static $wrap = 'users';

    /**
     * Transform the resource collection into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */
    public function toArray($request)
    {
        return $this->collection->map(fn($user) => UsersResource::make($user));
    }

    /**
     * Created
     *
     * @param $request
     * @param $paginated
     * @param $default
     * @return array
     */
    public function paginationInformation($request, $paginated, $default): array
    {
        return [
            'page' => $paginated['current_page'],
            'total_pages' => $paginated['last_page'],
            'total_users' => $paginated['total'],
            'count' => $paginated['to'] - $paginated['from'] + 1,
            'links' => [
                'prev' => $paginated['prev_page_url'] ?? null,
                'next' => $paginated['next_page_url'] ?? null,
            ]
        ];
    }

//
//    protected function preparePaginatedResponse($request)
//    {
//        return parent::preparePaginatedResponse($request); // TODO: Change the autogenerated stub
//    }
}
